/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'filename' : IDL.Text,
  'altText' : IDL.Text,
});
export const MenuCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Address = IDL.Record({
  'region' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
});
export const RestaurantProfile = IDL.Record({
  'owner' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'googleMapsLink' : IDL.Text,
  'address' : Address,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addMenuCategory' : IDL.Func([MenuCategory], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
  'deleteMenuCategory' : IDL.Func([IDL.Text], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantProfile' : IDL.Func([], [RestaurantProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
  'updateMenuCategory' : IDL.Func([MenuCategory], [], []),
  'updateMenuItem' : IDL.Func([MenuItem], [], []),
  'updateRestaurantProfile' : IDL.Func([RestaurantProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'filename' : IDL.Text,
    'altText' : IDL.Text,
  });
  const MenuCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Address = IDL.Record({
    'region' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
  });
  const RestaurantProfile = IDL.Record({
    'owner' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'googleMapsLink' : IDL.Text,
    'address' : Address,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addMenuCategory' : IDL.Func([MenuCategory], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
    'deleteMenuCategory' : IDL.Func([IDL.Text], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantProfile' : IDL.Func([], [RestaurantProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
    'updateMenuCategory' : IDL.Func([MenuCategory], [], []),
    'updateMenuItem' : IDL.Func([MenuItem], [], []),
    'updateRestaurantProfile' : IDL.Func([RestaurantProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };