/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'region' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
}
export interface GalleryImage {
  'id' : string,
  'filename' : string,
  'altText' : string,
}
export interface MenuCategory { 'id' : string, 'name' : string }
export interface MenuItem {
  'id' : string,
  'categoryId' : string,
  'name' : string,
  'description' : string,
  'price' : number,
}
export interface RestaurantProfile {
  'owner' : string,
  'name' : string,
  'description' : string,
  'googleMapsLink' : string,
  'address' : Address,
  'phoneNumber' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addMenuCategory' : ActorMethod<[MenuCategory], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryImage' : ActorMethod<[string], undefined>,
  'deleteMenuCategory' : ActorMethod<[string], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllMenuCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getRestaurantProfile' : ActorMethod<[], RestaurantProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'updateMenuCategory' : ActorMethod<[MenuCategory], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], undefined>,
  'updateRestaurantProfile' : ActorMethod<[RestaurantProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];